export type ProductDetailVM = {
  product: any;
  metadataDefinitions: any[];
  metadataValuesByKey: Record<string, any>;
  stockByLocation: any[];
  stockByBatch: any[];
  productChoices: any[];
  movements: any[];
  movementHeaders: any[];
  locationNameById: Record<number, string>;
  salePriceGroups: any[];
  usedInProducts: any[];
  costingAssemblies: any[];
  hasCmtLine?: boolean;
  pricingSpecOptions?: Array<{ value: string; label: string }>;
  categoryLabel?: string | null;
  subCategoryLabel?: string | null;
  subCategoryOptions?: Array<{ value: string; label: string }>;
  userLevel: string | null;
  canDebug: boolean;
};
