export type SheetController<T> = {
  value: T[];
  onChange?: (next: T[], operations?: unknown[]) => void;
  setValue?: (next: T[]) => void;
  rowClassName?: (args: { rowData: T; rowIndex: number }) => string | undefined;
  state?: { isDirty?: boolean };
  reset?: (next?: T[]) => void;
  commit?: () => void;
  getValues?: (opts?: { includeDeleted?: boolean }) => T[];
  undo?: () => any;
  redo?: () => any;
  beginTransaction?: (label?: string, uiBefore?: any) => void;
  commitTransaction?: (uiAfter?: any) => void;
  clearHistory?: () => void;
  applyDerivedPatch?: (updater: T[] | ((rows: T[]) => T[])) => void;
  replaceData?: (next: T[]) => void;
  triggerUndo?: () => void;
  triggerRedo?: () => void;
  onUndoRedo?: (kind: "undo" | "redo", source: "hotkey" | "button") => void;
  canUndo?: boolean;
  canRedo?: boolean;
  historyVersion?: number;
};
